modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"
issueTrackerURL="https://github.com/Minenash/Enhanced-Attack-Indicator-Forge/issues" #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL = "https://modrinth.com/mod/enhanced-attack-indicator" #optional
logoFile="enhanced_attack_indicator.png" #optional
authors = "${mod_authors}" #optional
#displayTest="IGNORE_ALL_VERSION"
description = '''${mod_description}'''#mandatory

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"